// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIImport.DAO;

#nullable disable

namespace WebAPIImport.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251104211726_RecordData")]
    partial class RecordData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIImport.DAO.Models.RecordData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value1")
                        .HasColumnType("int");

                    b.Property<int>("Value2")
                        .HasColumnType("int");

                    b.Property<int>("Value3")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tb_record_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
